[images]
  remote_images = ["https://same-assets.com/*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  command = "bun run dev"
  port = 3001
  targetPort = 3001

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/.pnpm/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
